name: My Workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Enter the environemnt Values (TEST, UAT, PROD)'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Log level is ${{ github.event.inputs.logLevel }}"
